name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    name: Perl ${{ matrix.perl-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-latest
        perl-version:
          - 5.20-buster
          - '5.30'
          - latest
          - threaded
    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: curl -L https://cpanmin.us | perl - App::cpanminus -v -n HTTP::Tiny Path::Tiny Archive::Extract strictures Data::Dump IO::Socket::SSL Net::SSLeay App::dumpbin FFI::ExtractSymbols FFI::CheckLib Module::Build::Tiny Alien::gmake Archive::Extract Carp::Always Alien::gmake FFI::Build
      - name: Run Tests
        #run: prove -l t
        run: perl sdl_libs.pl