name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl
        run: brew install perl
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: curl -L https://cpanmin.us | perl - App::cpanminus -v -n HTTP::Tiny Path::Tiny Archive::Extract strictures Data::Dump IO::Socket::SSL Net::SSLeay App::dumpbin FFI::ExtractSymbols FFI::CheckLib Module::Build::Tiny Alien::gmake Archive::Extract Carp::Always Alien::gmake FFI::Build
      - name: Run Tests
        #run: prove -l t
        run: perl sdl_libs.pl