name: windows (Strawberry Perl)

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'

jobs:
  perl-job:
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-latest]
        perl: [ '5.30', '5.32', 'latest' ]
        dist: [ 'strawberry' ]

    runs-on: ${{matrix.runner}}
    name: Perl ${{matrix.perl}} (${{ matrix.dist }})

    #container:
    #  image: perl:${{ matrix.perl-version }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up perl ${{ matrix.dist }} ${{ matrix.perl }}
      uses: shogo82148/actions-setup-perl@v1.11.0
      with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ matrix.dist }}

    - name: perl -V
      run: perl -V
    - name: Install Dependencies
      run: curl -L https://cpanmin.us | perl - App::cpanminus -v -n HTTP::Tiny Path::Tiny Archive::Extract strictures Data::Dump IO::Socket::SSL Net::SSLeay App::dumpbin FFI::ExtractSymbols FFI::CheckLib Module::Build::Tiny Alien::gmake Archive::Extract Carp::Always Alien::gmake FFI::Build
    - name: Run Tests
     #run: prove -l t
      run: perl sdl_libs.pl